/**
 * claude-generator.ts — LLM-powered CLAUDE.md generation for projects
 *
 * Uses Haiku to generate a structured CLAUDE.md file for each project.
 * Tracks staleness per project and regenerates on dispatch if stale.
 */

import type { WorkGraph } from '@/types/graph'
import type {
  ProjectEntity,
  TaskEntity,
  DeliveryEntity,
  DecisionEntity,
  NoteEntity,
} from '@/types/entities'
import { getClient, addTokenUsage, addCallRecord } from '@/lib/anthropic-client'

// ---------------------------------------------------------------------------
// Stale flag tracking
// ---------------------------------------------------------------------------

const _staleFlags: Map<string, boolean> = new Map()

export function markCLAUDEStale(projectSlug: string): void {
  _staleFlags.set(projectSlug, true)
}

export function markCLAUDEFresh(projectSlug: string): void {
  _staleFlags.set(projectSlug, false)
}

export function isProjectCLAUDEStale(projectSlug: string): boolean {
  // Unknown projects are considered stale (need initial generation)
  return _staleFlags.get(projectSlug) ?? true
}

// ---------------------------------------------------------------------------
// Prompt building (pure, testable)
// ---------------------------------------------------------------------------

const GENERATION_SYSTEM_PROMPT = `You are Twin, a personal context engine.

Generate a structured CLAUDE.md file for the given project. This file will be read
by Claude Code and Claude Chat at the start of every coding session.

Output ONLY the markdown content. No code fences. No preamble.

Use this exact structure:

# Project context — [project name]
_Generated by Twin · [today's date]_

## Project overview
[2-3 sentences from context.md]

## Current focus
[Bullet list of in-progress and high-priority tasks with IDs]

## Open decisions (active only)
[Bullet list of active decisions with IDs and one-line summary]

## Blocked items (include task IDs)
[Bullet list of blocked tasks with what they're blocked on]

## Deliveries in progress
| Delivery | Type | Status | Due |
|----------|------|--------|-----|
[Table rows for non-delivered, non-archived deliveries]

## Key constraints
[Bullet list from context.md constraints]

## Pick up here
[1-2 sentences: what to work on next based on priorities and blockers]

---
_Source files: context.md · tasks.yaml · deliveries.yaml · decisions.yaml · notes/_
_Do not edit this file — it is regenerated by Twin._
_Append decisions to decisions.yaml. Edit tasks in tasks.yaml._`

export type NoteSummary = {
  title: string
  body: string
}

export function buildGenerationPrompt(
  projectSlug: string,
  graph: WorkGraph,
  contextMd: string,
  notesSummaries: NoteSummary[],
): { system: string; userMessage: string } {
  const tasks = graph.entities.filter(
    (e): e is TaskEntity => e.kind === 'task' && e.project === projectSlug,
  )
  const deliveries = graph.entities.filter(
    (e): e is DeliveryEntity => e.kind === 'delivery' && e.project === projectSlug,
  )
  const activeDecisions = graph.entities.filter(
    (e): e is DecisionEntity =>
      e.kind === 'decision' && e.project === projectSlug && e.status === 'active',
  ).slice(-10)
  const project = graph.entities.find(
    (e): e is ProjectEntity => e.kind === 'project' && e.slug === projectSlug,
  )

  const lines: string[] = []

  lines.push(`=== PROJECT: ${projectSlug} ===`)
  if (project) {
    lines.push(`Name: ${project.name}`)
  }
  lines.push('')

  lines.push('=== context.md ===')
  lines.push(contextMd)
  lines.push('')

  lines.push('=== tasks.yaml (full, with IDs) ===')
  for (const t of tasks) {
    let line = `- [${t.id}] ${t.title} | status: ${t.status} | priority: ${t.priority}`
    if (t.due_date) line += ` | due: ${t.due_date}`
    if (t.blocked_by) line += ` | blocked_by: ${t.blocked_by}`
    if (t.waiting_on) line += ` | waiting_on: ${t.waiting_on}`
    if (t.delivery) line += ` | delivery: ${t.delivery}`
    lines.push(line)
  }
  lines.push('')

  lines.push('=== deliveries.yaml (full) ===')
  for (const d of deliveries) {
    let line = `- [${d.id}] ${d.title} | type: ${d.type} | status: ${d.status}`
    if (d.due_date) line += ` | due: ${d.due_date}`
    if (d.brief) line += ` | brief: ${d.brief}`
    lines.push(line)
  }
  lines.push('')

  lines.push('=== decisions.yaml (active only, last 10) ===')
  for (const d of activeDecisions) {
    lines.push(`- [${d.id}] ${d.title}: ${d.decision}`)
    if (d.rationale) lines.push(`  Rationale: ${d.rationale}`)
  }
  lines.push('')

  lines.push('=== Twin-synced notes (title + first 200 chars) ===')
  if (notesSummaries.length === 0) {
    lines.push('No synced notes.')
  } else {
    for (const n of notesSummaries) {
      const truncated = n.body.slice(0, 200)
      lines.push(`- ${n.title}: ${truncated}`)
    }
  }

  return {
    system: GENERATION_SYSTEM_PROMPT,
    userMessage: lines.join('\n'),
  }
}

// ---------------------------------------------------------------------------
// LLM call
// ---------------------------------------------------------------------------

export async function generateProjectCLAUDE(
  projectSlug: string,
  graph: WorkGraph,
): Promise<string> {
  // Read context.md from the project folder
  const { readTextFile, exists } = await import('@tauri-apps/plugin-fs')
  const { projectPath } = await import('./paths')
  const { join } = await import('@tauri-apps/api/path')

  const projPath = await projectPath(projectSlug)
  const contextPath = await join(projPath, 'context.md')

  let contextMd = ''
  try {
    const contextExists = await exists(contextPath)
    if (contextExists) {
      contextMd = await readTextFile(contextPath)
    }
  } catch {
    // context.md may not exist — proceed with empty
  }

  // Build note summaries from twin-synced notes in the graph
  const notes = graph.entities.filter(
    (e): e is NoteEntity =>
      e.kind === 'note' && e.project === projectSlug && e.twin_synced,
  )

  const notesSummaries: NoteSummary[] = []
  for (const note of notes) {
    try {
      const notePath = await join(projPath, 'notes', note.filename)
      const noteContent = await readTextFile(notePath)
      // Extract body (after frontmatter)
      const bodyMatch = noteContent.match(/---[\s\S]*?---\s*([\s\S]*)/)
      const body = bodyMatch ? bodyMatch[1].trim() : noteContent
      notesSummaries.push({ title: note.title, body: body.slice(0, 200) })
    } catch {
      // Note file may not be readable — skip
      notesSummaries.push({ title: note.title, body: '' })
    }
  }

  const prompt = buildGenerationPrompt(projectSlug, graph, contextMd, notesSummaries)
  const start = Date.now()

  try {
    const response = await getClient().messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 2048,
      system: prompt.system,
      messages: [{ role: 'user', content: prompt.userMessage }],
    })

    const duration = Date.now() - start
    const textContent = response.content
      .filter((block) => block.type === 'text')
      .map((block) => block.text)
      .join('')

    const usage = {
      input_tokens: response.usage.input_tokens,
      output_tokens: response.usage.output_tokens,
      cache_read_tokens:
        (response.usage as unknown as Record<string, number>).cache_read_input_tokens ?? 0,
      cache_creation_tokens:
        (response.usage as unknown as Record<string, number>).cache_creation_input_tokens ?? 0,
    }

    addTokenUsage(usage, 'claude-haiku-4-5-20251001')
    addCallRecord({
      agent: 'claude-generator',
      model: 'claude-haiku-4-5-20251001',
      timestamp: start,
      usage,
      duration_ms: duration,
      success: true,
    })

    return textContent
  } catch (error) {
    const duration = Date.now() - start
    console.error('CLAUDE.md generation API error:', error)

    addCallRecord({
      agent: 'claude-generator',
      model: 'claude-haiku-4-5-20251001',
      timestamp: start,
      usage: { input_tokens: 0, output_tokens: 0, cache_read_tokens: 0, cache_creation_tokens: 0 },
      duration_ms: duration,
      success: false,
      error: error instanceof Error ? error.message : String(error),
    })

    throw error
  }
}

// ---------------------------------------------------------------------------
// Regenerate if stale
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Delta-aware stale marking
// ---------------------------------------------------------------------------

/**
 * Given a delta operation, extract the project slug and mark that project's
 * CLAUDE.md as stale. Call this after applying any delta.
 */
export function markStaleForDelta(delta: { op: string; [key: string]: unknown }): void {
  // Extract project slug from the delta
  let projectSlug: string | undefined

  if ('payload' in delta && typeof delta.payload === 'object' && delta.payload !== null) {
    const payload = delta.payload as Record<string, unknown>
    if (typeof payload.project === 'string' && payload.project) {
      projectSlug = payload.project
    }
  }
  if (!projectSlug && typeof delta.project === 'string' && delta.project) {
    projectSlug = delta.project
  }

  if (projectSlug) {
    markCLAUDEStale(projectSlug)
  }
}

// ---------------------------------------------------------------------------
// Regenerate if stale
// ---------------------------------------------------------------------------

export async function regenerateIfStale(
  projectSlug: string,
  graph: WorkGraph,
): Promise<void> {
  if (!isProjectCLAUDEStale(projectSlug)) return

  try {
    const content = await generateProjectCLAUDE(projectSlug, graph)
    const { writeProjectCLAUDE } = await import('./fs')
    await writeProjectCLAUDE(projectSlug, content)
    markCLAUDEFresh(projectSlug)
  } catch (error) {
    // Graceful degradation — log and continue without blocking dispatch
    console.error(`[claude-generator] Failed to regenerate CLAUDE.md for ${projectSlug}:`, error)
  }
}
